name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows-installer-msi:
    name: Build Windows x64 installer (MSI)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 24
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with JPackage
        run: ./gradlew jpackage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/distributions/Replay Reader-*.msi
          name: windows-installer-msi
          retention-days: 1

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - build-windows-installer-msi
    steps:
      - name: Download Windows x64 installer (MSI)
        uses: actions/download-artifact@v4
        with:
          name: windows-installer-msi

      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            *.msi

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            checksum.txt
            *.msi
          token: "${{ secrets.GITHUB_TOKEN }}"